version: "3.8"
services:
  # web-client:
  #   build: ./client/
  #   networks:
  #     - frontend
  #   volumes:
  #     # - ./docker/www/www.loconnected.com:/app/dist
  #     # - ./docker/www/www.loconnected.com:/app
  #   tty: true

  # web-admin:
  #   build: ./admin/
  #   networks:
  #     - frontend
  #   volumes:
  #     # - ./docker/www/admin.loconnected.com:/app/dist
  #   tty: true

  db:
    image: mariadb
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: test

    volumes:
      - ./docker/database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: adminer
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce

  node-api:
    build: ./server/
    image: node-api
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      - backend
    depends_on:
      - db

  nginx-server:
    image: nginx:mainline-alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx
      - ./docker/www:/var/www:ro
      # - ./docker/certbot/conf:/etc/letsencrypt
      # - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - node-api

    networks:
      - backend
      # - frontend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx-server
  #   volumes:
  #     - ./docker/certbot/conf:/etc/letsencrypt
  #     - ./docker/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge
